---
  vlm_api_options:
    - value: 'openai_compatible'
      name: 'OpenAI Compatible'
    - value: 'openai'
      name: 'OpenAI'
    - value: 'azure_openai'
      name: 'Azure OpenAI'
    - value: 'ollama'
      name: 'Ollama'