site_name: VLM4OCR Documentation
theme:
    name: material
    features:
      - content.code.highlight

nav:
    - 'Home': 'index.md'
    - 'Web Application': 'web_application.md'
    - 'CLI': 'cli.md' 
    - 'Python package':
      - 'Quick Start': 'quick_start.md'
      - 'VLM Engines': 'vlm_engines.md'
      - 'OCR Engine': 'ocr_engine.md'
    - 'API Reference':
      - 'VLM Engines': 'api/vlm_engines.md'
      - 'OCR Engine': 'api/ocr_engine.md'
      - 'CLI': 'api/cli.md'
      
plugins:
    - search
    - gen-files:
        scripts:
          - docs/generate_cli_docs.py
    - mkdocs-video
    - mkdocstrings:
        handlers:
          python:
            options:
              docstring_style: numpy
              show_root_heading: true
              show_source: true
              members_order: source
              separate_signature: true
              show_signature_annotations: true
              show_docstring_annotations: true
              merge_init_into_class: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences